routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\ForumController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('home');
}); */


Route::get('/',  HomeController::class)->name('home');
Route::get('nosotros',  HomeController::class)->name('nosotros');
/* Rutas de curso */
Route::get('course', [ CourseController::class,'index'])->name('course.index');

Route::get('course/create', [ CourseController::class,'create'])->name('course.create');

Route::post('course/', [ CourseController::class,'store'])->name('course.store');

Route::get('course/texto',[CourseController::class,'texto'])->name('course.texto');

Route::get('course/{course}', [ CourseController::class,'show'])->name('course.show');

/* Rutas del post */
Route::get('post', [ PostController::class,'post'])->name('post');

Route::get('post', [ PostController::class,'index'])->name('post.index');

Route::get('post/create', [ PostController::class,'create'])->name('post.create');

Route::post('post/', [ PostController::class,'store'])->name('post.store');

Route::get('post/{post}', [ PostController::class,'show'])->name('post.show');

/* Rutas del foro */
Route::get('forum', [ ForumController::class,'forum'])->name('forum');

Route::get('forum', [ ForumController::class,'index'])->name('forum.index');

Route::get('forum/create', [ ForumController::class,'create'])->name('forum.create');

Route::post('forum/', [ ForumController::class,'store'])->name('forum.store');

Route::get('forum/{post}', [ ForumController::class,'show'])->name('forum.show');

/* Rutas del comentarios */
Route::get('comment', [ CommentController::class,'comment'])->name('comment');

Route::get('comment', [ CommentController::class,'index'])->name('comment.index');

Route::get('comment/create', [ CommentController::class,'create'])->name('comment.create');

Route::post('comment/', [ CommentController::class,'store'])->name('comment.store');

Route::get('comment/{comment}', [ CommentController::class,'show'])->name('comment.show');

/* Ruta de category */
Route::get('category', [ CategoryController::class,'category'])->name('category');

Route::get('category', [ CategoryController::class,'index'])->name('category.index');

Route::get('category/create', [ CategoryController::class,'create'])->name('category.create');

Route::post('category/', [ CategoryController::class,'store'])->name('category.store');

Route::get('category/{category}', [ CategoryController::class,'show'])->name('category.show');


Route::resource('course', CourseController::class);
Route::resource('post',PostController::class);
Route::resource('forum',ForumController::class);
Route::resource('comment',CommentController::class);
Route::resource('category',CategoryController::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('') }}
        </h2>
    </x-slot>

    {{-- <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div> --}}
            <div class="py-8">
                <div class="max-w-7xl mx-auto sm:px-3 lg:px-8">
                
            {{-- @livewire('forums-component') --}}
            @livewire('category-component')
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
@extends('layouts.web')
@section('title','home')

@section('content') 


<body class="bg-gray-100">
<div class="bg-cover bg-center text-center " style="height:32rem; background-image: url(https://images.unsplash.com/photo-1504384308090-c894fdcc538d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
      <div class="flex items-center text-gray-500 font-bold text-center xl justify-center h-full max-w-7xl bg-gray-900 bg-opacity-50">¡CODIFICANDO EL FUTURO!</div>


<div class="min-h-screen flex flex-col flex-auto flex-shrink-0 antialiased bg-gray-50 text-gray-800">
  <div class="fixed flex flex-col top-0 left-0 w-64 bg-gray-900 h-full shadow-lg">
      <div class="flex items-center pl-6 h-20 border-b border--gray-100">
        <div class="flex flex-row items-center h-8"><img class=" bg-gray-500 inline" src="../css/src/user-circle.svg">
          <div class="flex font-semibold text-sm text-gray-300 my-4 font-sans uppercase p-2"><a href="{{ url('/dashboard') }}">CATEGORIAS</div>
      </div>
      </div>
      <div class="overflow-y-auto overflow-x-hidden flex-grow">
        
      <ul class="flex flex-col py-6 space-y-1">
          
      
          <li class="flex flex-row items-center h-8">
              <a href="{{ route('home')}}"class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-700 text-gray-500 hover:text-gray-200 border-l-4 border-transparent hover:border-blue-500 pr-6"><img class="inline-flex justify-center items-center ml-4" src="../css/src/home.svg"><span class="ml-2 font-semibold text-sm tracking-wide truncate font-sans">Inicio</span>
              </a>
          </li>
          <li>
            <div class= "group inline-block">
              <li class="flex flex-row items-center h-8 ">
                <a href="{{route('course.index')}}"class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-700 text-gray-500 hover:text-gray-200 border-l-4 border-transparent hover:border-blue-500 pr-6"><img class="inline-flex justify-center items-center ml-4" src="../css/src/archive.svg"><span class="ml-2 font-semibold text-sm tracking-wide truncate font-sans">Cursos</span>
                      <li class="rounded-sm px-3 py-2 hover:bg-gray-100"><a href="{{route('forum.index')}}" class="block mx-4 mt-2 md:mt-0 text-sm text-gray-700 capitalize hover:text-blue-600">Web developers</a></li>
                      <li class="rounded-sm px-3 py-1 hover:bg-gray-100"><a href="{{route('forum.index')}}" class="block mx-4 mt-2 md:mt-0 text-sm text-gray-700 capitalize hover:text-blue-600">Web Designers</a></li>
                      <li class="rounded-sm px-3 py-1 hover:bg-gray-100"><a href="{{route('forum.index')}}" class="block mx-4 mt-2 md:mt-0 text-sm text-gray-700 capitalize hover:text-blue-600">UI/UX Designers</a></li>
                      <li class="rounded-sm px-3 py-1 hover:bg-gray-100"><a href="{{route('nosotros')}}" class="block mx-4 mt-2 md:mt-0 text-sm text-gray-700 capitalize hover:text-blue-600">Contacto</a></li>
                </a>
              </li>
            
            
          <li class="flex flex-row items-center h-8">
            <a href="{{route('post.index')}}"class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-700 text-gray-500 hover:text-gray-200 border-l-4 border-transparent hover:border-blue-500 pr-6"><img class="inline-flex justify-center items-center ml-4" src="../css/src/users.svg"><span class="ml-2 font-semibold text-sm tracking-wide truncate font-sans">Post</span>
            </a>
        </li> 
        <li class="flex flex-row items-center h-8">
          <a href="{{route('forum.index')}}"class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-700 text-gray-500 hover:text-gray-200 border-l-4 border-transparent hover:border-blue-500 pr-6"><img class="inline-flex justify-center items-center ml-4" src="../css/src/globe.svg"><span class="ml-2 font-semibold text-sm tracking-wide truncate font-sans">Foros</span>
          </a>
      </li> 
      <li class="flex flex-row items-center h-8">
        <a href="{{route('comment.index')}}"class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-700 text-gray-500 hover:text-gray-200 border-l-4 border-transparent hover:border-blue-500 pr-6"><img class="inline-flex justify-center items-center ml-4" src="../css/src/hand.svg"><span class="ml-2 font-semibold text-sm tracking-wide truncate font-sans">Comentarios</span>
        </a>
    </li>  
           
          <li class="px-5">
          <div class="flex flex-row items-center h-8">
              <div class="flex font-semibold text-sm text-gray-300 my-4 font-sans uppercase">Settings</div>
          </div>
          </li>
          <li>
          <a href="{{ route('login') }}" class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-700 text-gray-500 hover:text-gray-200 border-l-4 border-transparent hover:border-blue-500 pr-6">
              <span class="inline-flex justify-center items-center ml-4">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
              </span>
              <span class="ml-2 font-semibold text-sm tracking-wide truncate font-sans">Perfil</span>
          </a>
          </li>
          </ul>
        </div>
      </div>
  
</div>
</div>
</div>
<!-- divide -->
<hr class="my-6 "> 
{{-- card --}}

    <div class="max-w-4xl mx-auto sm:px-6 lg:px-8 mr-12">
    <div class="overflow-hidden shadow-md">
        <!-- card header -->
        <div class="px-6 py-4 bg-gray-800 border-b border-gray-200 font-bold uppercase text-gray-300">
            Web developers
        </div>

        <!-- card body -->
        <div class="p-6 bg-white border-b border-gray-400">
            <!-- content goes here -->
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
            when an unknown printer took a galley of type and scrambled it to make a type 
            specimen book.
        </div>

        <!-- card footer -->
        <div class="p-6 bg-white border-gray-200 text-right">
            <!-- button link -->
            <a class="bg-gray-700 shadow-md text-sm text-white font-bold py-3 md:px-8 px-4 hover:bg-blue-400 rounded uppercase" 
                href="{{route('course.index')}}">Click Aca</a>
        </div>
    </div>
</div>

<!-- divide -->
<hr class="my-6"> 

<!-- dark mode -->
<div class="max-w-4xl mx-auto sm:px-6 lg:px-8 mr-12">
    <div class="overflow-hidden shadow-md text-gray-100">
        <!-- card header -->
        <div class="px-6 py-4 bg-gray-800 border-b border-gray-600 font-bold uppercase">
            Seminarios
        </div>

        <!-- card  body -->
        <div class="p-6 bg-gray-800 border-b border-gray-600">
            <!-- content goes here -->
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
            when an unknown printer took a galley of type and scrambled it to make a type 
            specimen book.
        </div>

        <!-- card footer -->
        <div class="p-6 bg-gray-800 border-gray-200 text-right">
            <!-- button link -->
            <a class="bg-gray-700 shadow-md text-sm text-white font-bold py-3 md:px-8 px-4 hover:bg-blue-400 rounded uppercase" 
                href="{{route('post.index')}}">Click Aca</a>
        </div>
    </div>
</div>
    
        
  
   </body>
   <!-- divide -->
   <hr class="my-6">  
  <footer>
    <section class="bg-gray-700 py-8 w-full border-white">
      <div class="container mx-auto px-8">
          <div class="table w-full">
              <div class="block sm:table-cell">
                  <p class="uppercase text-grey text-sm sm:mb-6">Links</p>
                  <ul class="list-reset text-xs mb-6">
                      <li class="mt-2 inline-block mr-2 sm:block sm:mr-0">
                          <a href="#" class="text-grey hover:text-grey-dark">preguntas frecuentes</a>
                      </li>
                      <li class="mt-2 inline-block mr-2 sm:block sm:mr-0">
                          <a href="#" class="text-grey hover:text-grey-dark">Ayuda</a>
                      </li>
                      <li class="mt-2 inline-block mr-2 sm:block sm:mr-0">
                          <a href="#" class="text-grey hover:text-grey-dark">Soporte</a>
                      </li>
                  </ul>
              </div>
              <div class="block sm:table-cell">
                  <p class="uppercase text-grey text-sm sm:mb-6">Legal</p>
                  <ul class="list-reset text-xs mb-6">
                      <li class="mt-2 inline-block mr-2 sm:block sm:mr-0">
                          <a href="#" class="text-grey hover:text-grey-dark">Terminos</a>
                      </li>
                      <li class="mt-2 inline-block mr-2 sm:block sm:mr-0">
                          <a href="#" class="text-grey hover:text-grey-dark">Privacidad</a>
                      </li>
                  </ul>
              </div>
              <div class="block sm:table-cell">
                  <p class="uppercase text-grey text-sm sm:mb-6">Social</p>
                  <ul class="list-reset text-xs mb-6">
                      <li class="mt-2 inline-block mr-2 sm:block sm:mr-0">
                          <a href="#" class="text-grey hover:text-grey-dark">Facebook</a>
                      </li>
                      <li class="mt-2 inline-block mr-2 sm:block sm:mr-0">
                          <a href="#" class="text-grey hover:text-grey-dark">Linkedin</a>
                      </li>
                      <li class="mt-2 inline-block mr-2 sm:block sm:mr-0">
                          <a href="#" class="text-grey hover:text-grey-dark">Twitter</a>
                      </li>
                  </ul>
              </div>
              <div class="block sm:table-cell">
                  <p class="uppercase text-grey text-sm sm:mb-6">La Compañia</p>
                  <ul class="list-reset text-xs mb-6">
                      
                      <li class="mt-2 inline-block mr-2 sm:block sm:mr-0">
                          <a href="{{route('nosotros')}}" class="text-grey hover:text-grey-dark">Nosotros</a>
                        </li>
                      <li class="mt-2 inline-block mr-2 sm:block sm:mr-0">
                          <a href="#" class="text-grey hover:text-grey-dark">Contactanos</a>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
  </section>
  </footer>

    
     
      
        

 
@endsection

resources/views/navigation-menu.blade.php
<nav x-data="{ open: false }" class="bg-gray-900 border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-32">
            <div class="flex">
                <!-- Logo -->
              {{--   <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-jet-application-mark class="block h-9 w-auto" />
                    </a>
                </div> --}}
                <img
           src="{{ asset('img/logo.png') }}" 
           class="rounded h-13 mx-left">

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex bg-gray-300">
                    <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                        {{ __('Tu Tablero') }}
                    </x-jet-nav-link>
                </div>
            </div>

            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <!-- Teams Dropdown -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="ml-3 relative">
                        <x-jet-dropdown align="right" width="60">
                            <x-slot name="trigger">
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:bg-gray-50 hover:text-gray-700 focus:outline-none focus:bg-gray-50 active:bg-gray-50 transition">
                                        {{ Auth::user()->currentTeam->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            </x-slot>

                            <x-slot name="content ">
                                <div class="w-60 ">
                                    <!-- Team Management -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Manage Team') }}
                                    </div>

                                    <!-- Team Settings -->
                                    <x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">
                                        {{ __('Team Settings') }}
                                    </x-jet-dropdown-link>

                                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                        <x-jet-dropdown-link href="{{ route('teams.create') }}">
                                            {{ __('Create New Team') }}
                                        </x-jet-dropdown-link>
                                    @endcan

                                    <div class="border-t border-gray-300"></div>

                                    <!-- Team Switcher -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Switch Teams') }}
                                    </div>

                                    @foreach (Auth::user()->allTeams() as $team)
                                        <x-jet-switchable-team :team="$team" />
                                    @endforeach
                                </div>
                            </x-slot>
                        </x-jet-dropdown>
                    </div>
                @endif

                <!-- Settings Dropdown -->
                <div class="ml-3 relative">
                    <x-jet-dropdown align="right" width="48">
                        <x-slot name="trigger">
                            @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                                <button class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition">
                                    <img class="h-12 w-12 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                                </button>
                            @else
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-gray-300 hover:text-gray-700 focus:outline-none transition">
                                        {{ Auth::user()->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            @endif
                        </x-slot>

                        <x-slot name="content">
                            <!-- Account Management -->
                            <div class="block px-4 py-2 text-sm text-gray-500">
                                {{ __('Administrar cuenta') }}
                            </div>

                            <x-jet-dropdown-link href="{{ route('profile.show') }}">
                                {{ __('Perfil') }}
                            </x-jet-dropdown-link>

                            @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                                <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                    {{ __('API Tokens') }}
                                </x-jet-dropdown-link>
                            @endif

                            <div class="border-t border-gray-400"></div>

                            <!-- Authentication -->
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <x-jet-dropdown-link href="{{ route('logout') }}"
                                         onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                    {{ __('Cerrar sesión') }}
                                </x-jet-dropdown-link>
                            </form>
                        </x-slot>
                    </x-jet-dropdown>
                </div>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-jet-responsive-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-jet-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                    <div class="flex-shrink-0 mr-3">
                        <img class="h-10 w-10 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                    </div>
                @endif

                <div>
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Account Management -->
                <x-jet-responsive-nav-link href="{{ route('profile.show') }}" :active="request()->routeIs('profile.show')">
                    {{ __('Profile') }}
                </x-jet-responsive-nav-link>

                @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                    <x-jet-responsive-nav-link href="{{ route('api-tokens.index') }}" :active="request()->routeIs('api-tokens.index')">
                        {{ __('API Tokens') }}
                    </x-jet-responsive-nav-link>
                @endif

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-jet-responsive-nav-link href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                    this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-jet-responsive-nav-link>
                </form>

                <!-- Team Management -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="border-t border-gray-200"></div>

                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Manage Team') }}
                    </div>

                    <!-- Team Settings -->
                    <x-jet-responsive-nav-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}" :active="request()->routeIs('teams.show')">
                        {{ __('Team Settings') }}
                    </x-jet-responsive-nav-link>

                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                        <x-jet-responsive-nav-link href="{{ route('teams.create') }}" :active="request()->routeIs('teams.create')">
                            {{ __('Create New Team') }}
                        </x-jet-responsive-nav-link>
                    @endcan

                    <div class="border-t border-gray-200"></div>

                    <!-- Team Switcher -->
                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Switch Teams') }}
                    </div>

                    @foreach (Auth::user()->allTeams() as $team)
                        <x-jet-switchable-team :team="$team" component="jet-responsive-nav-link" />
                    @endforeach
                @endif
            </div>
        </div>
    </div>
</nav>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>