routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\ForumController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('home');
}); */


Route::get('/',  HomeController::class)->name('home');
Route::get('nosotros',  HomeController::class)->name('nosotros');
/* Rutas de curso */
Route::get('course', [ CourseController::class,'index'])->name('course.index');

Route::get('course/create', [ CourseController::class,'create'])->name('course.create');

Route::post('course/', [ CourseController::class,'store'])->name('course.store');

Route::get('course/texto',[CourseController::class,'texto'])->name('course.texto');

Route::get('course/{course}', [ CourseController::class,'show'])->name('course.show');

/* Rutas del post */
Route::get('post', [ PostController::class,'post'])->name('post');

Route::get('post', [ PostController::class,'index'])->name('post.index');

Route::get('post/create', [ PostController::class,'create'])->name('post.create');

Route::post('post/', [ PostController::class,'store'])->name('post.store');

Route::get('post/{post}', [ PostController::class,'show'])->name('post.show');

/* Rutas del foro */
Route::get('forum', [ ForumController::class,'forum'])->name('forum');

Route::get('forum', [ ForumController::class,'index'])->name('forum.index');

Route::get('forum/create', [ ForumController::class,'create'])->name('forum.create');

Route::post('forum/', [ ForumController::class,'store'])->name('forum.store');

Route::get('forum/{post}', [ ForumController::class,'show'])->name('forum.show');

/* Rutas del comentarios */
Route::get('comment', [ CommentController::class,'comment'])->name('comment');

Route::get('comment', [ CommentController::class,'index'])->name('comment.index');

Route::get('comment/create', [ CommentController::class,'create'])->name('comment.create');

Route::post('comment/', [ CommentController::class,'store'])->name('comment.store');

Route::get('comment/{comment}', [ CommentController::class,'show'])->name('comment.show');

/* Ruta de category */
Route::get('category', [ CategoryController::class,'category'])->name('category');

Route::get('category', [ CategoryController::class,'index'])->name('category.index');

Route::get('category/create', [ CategoryController::class,'create'])->name('category.create');

Route::post('category/', [ CategoryController::class,'store'])->name('category.store');

Route::get('category/{category}', [ CategoryController::class,'show'])->name('category.show');


Route::resource('course', CourseController::class);
Route::resource('post',PostController::class);
Route::resource('forum',ForumController::class);
Route::resource('comment',CommentController::class);
Route::resource('category',CategoryController::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Course
 *
 * @property $id
 * @property $user_id
 * @property $title
 * @property $description
 * @property $image
 * @property User $user
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */


class Category extends Model
{
    use HasFactory;
    static $rules = [
       
        'title' => 'required',
        'description'=> 'required',
        'imagen'=> 'required',
    ];

    protected $perPage = 20;
 
    protected $fillable =[
        'user_id',
        'title',
        'description',
        'imagen',

    ];
    
    public function category()
    {
       /*  return $this->belongsTo(Category::class); */
 /*       return $this->hasOne('App\Models\Category', 'id'); */
       
    }

    public function comment()
    {
        return $this->hasMany('App\Models\Comment', 'category_id', 'id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function course()
    {
        return $this->hasMany('App\Models\Course', 'category_id', 'id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function forum()
    {
        return $this->hasMany('App\Models\Forum', 'category_id', 'id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function post()
    {
        return $this->hasMany('App\Models\Post', 'category_id', 'id');
    }
    

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

/**
 * Class CategoryController
 * @package App\Http\Controllers
 */
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::all();

        return view('category.index', compact('category'));
            
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = new Category();
        return view('category.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)

    {    
        request()->validate(Category::$rules);
       
       
        $category = Category::create($request->all());

        return redirect()->route('category.index')
        ->with('success', 'Has creado una Categoría');
    }

       
       

       
    

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);

        return view('category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);

        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        request()->validate(Category::$rules);

        $category->update($request->all());

        return redirect()->route('category.index')
            ->with('success', 'creado con éxito');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $category = Category::find($id)->delete();

        return redirect()->route('category.index')
            ->with('success', 'Category deleted successfully');
    }
}

resources/views/category/create.blade.php
@extends('layouts.web')

@section('title','crear')


@section('content')
    <section class="content container-fluid">

        <div class="shadow-xl p-10 bg-gray-300 max-w-64 mt-8 rounded">
            <div class="w-full px-3 mr-2 text-center text-gray-800 font-bold text-xl mb-2  bg-gray-600">

                @includeif('partials.errors')

              
                    <div class="card-header ">
                        <span class="card-title">Crear una Categoria</span>
                    </div>
                    <div class="card-body">
                        <form class="p-5 " method="POST" action="{{ route('category.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('category.form')
                            
                        </form>
                    </div>
                    
            </div>
        </div>
    </section>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.web')

@section('title','Editar')
{{--     Update Category
@endsection --}}

@section('content')
    <section class="content container-fluid">
        <div class="shadow-xl p-10 bg-gray-300 max-w-64 mt-8 rounded">
            <div class="col-md-12 w-full px-3 mr-2 text-center text-gray-800 font-bold text-xl mb-2  bg-gray-600">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Actualizar categoría</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('category.update', $category->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('category.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/category/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body py-8 mx-auto max-w-screen-xl  sm:flex flex-grow-0 sm:p-5">
        <div class="form-group">
            {{ Form::label('user_id') }}
            {{ Form::text('user_id', $category->user_id, ['class' => 'form-control' . ($errors->has('user_id') ? ' is-invalid' : ''), 'placeholder' => 'User Id']) }}
            {!! $errors->first('user_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group ml-12">
            {{ Form::label('Titulo') }}
            {{ Form::text('title', $category->title, ['class' => 'form-control' . ($errors->has('title') ? ' is-invalid' : ''), 'placeholder' => 'Titulo']) }}
            {!! $errors->first('title', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Descripción') }}
            {{ Form::text('description', $category->description, ['class' => 'form-control' . ($errors->has('description') ? ' is-invalid' : ''), 'placeholder' => 'Descripción']) }}
            {!! $errors->first('description', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Imagen') }}
            {{ Form::text('image', $category->image, ['class' => 'form-control' . ($errors->has('image') ? ' is-invalid' : ''), 'placeholder' => 'Imagen']) }}
            {!! $errors->first('image', '<div class="invalid-feedback">:message</p>') !!}
        </div>
     {{--    <div class="form-group">
            {{ Form::label('last_used_at') }}
            {{ Form::text('last_used_at', $category->last_used_at, ['class' => 'form-control' . ($errors->has('last_used_at') ? ' is-invalid' : ''), 'placeholder' => 'Last Used At']) }}
            {!! $errors->first('last_used_at', '<div class="invalid-feedback">:message</p>') !!}
        </div> --}}

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
</div>

resources/views/category/index.blade.php
@extends('layouts.web')

@section('title','Categorias')



@section('content')
<h1 class="text-center text-white  font-bold text-xl mb-2 bg-gray-900">CATEGORIAS</h1>
<section class="px-4 sm:px-6 lg:px-4 xl:px-6 pt-4 pb-4 sm:pb-6 lg:pb-4 xl:pb-6 space-y-4">
    <header class="justify-between">
        <div class="w-full lg:max-w-full lg:flex">
            <div class="h-48 lg:h-auto lg:w-58 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden">
            </div>
            <img class="w-full h-64 rounded-b rounded-t mb-4 " src="{{ asset('img/categoria.jpg') }}">    
        
      <button class="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-4 py-2">
        <svg class="group-hover:text-light-blue-600 text-light-blue-500 mr-2" width="12" height="20" fill="currentColor">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M6 5a1 1 0 011 1v3h3a1 1 0 110 2H7v3a1 1 0 11-2 0v-3H2a1 1 0 110-2h3V6a1 1 0 011-1z"/>
        </svg>
         <div class="float-right p-2 bg-gray-900 text-gray-200 ">
            <a href="{{ route('category.create') }}"data-placement="left">
              {{ __('Crear una Categoria') }}
            </a>
          </div>
      </button>
    </header>
    <form class="relative">
      <svg width="20" height="20" fill="currentColor" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400">
        <path fill-rule="evenodd" clip-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" />
      </svg>
      <input wire:model= " search" class=" form-control focus:border-light-blue-500 focus:ring-1 focus:ring-light-blue-500 focus:outline-none w-full text-sm text-black placeholder-gray-500 border border-gray-300 rounded-md py-2 pl-10" type="text" aria-label="Filter projects" placeholder="Filtrar categoria" />
    </form>
    <div class="container-fluid ">
        <div class="row border">
            <div class="col-sm-12">
                <div class="card shadow-2xl">
                    <div class="card-header text-center  rounded-full font-bold text-xl mb-8">
           
                    
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body  grid grid-cols-1 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-1 md-8 gap-4">
                        <div class="table-responsive md:grid-rows-6 border-gray-900">
                            <table class="min-w-full divide-y divide-gray-900 border bg-gray-500 ">
                                <thead class="thead ">
                                    <tr>
                                        {{-- <th>No</th> --}}
                                        <th scope="col" class="px-6 py-3 text-center text-l font-bold  text-gray-900 uppercase tracking-wider">Id</th>
										<th scope="col" class="px-6 py-3 text-center text-l font-bold  text-gray-900 uppercase tracking-wider">titulo</th>
										<th scope="col" class="px-6 py-3 text-center text-l font-bold  text-gray-900 uppercase tracking-wider">Descripción</th>
										<th scope="col" class="px-6 py-3 text-left text-l font-bold  text-gray-900 uppercase tracking-wider">Imagen</th>
										{{-- <th>Last Used At</th> --}}

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody class="text-center w-full lg:max-w-full  lg:divide-y divide-gray-400">
                                    @foreach ($category as $category)
                                    <div class="bg-gray-200 shadow-lg rounded-lg  text-center ">
                                        <tr>
                                           
                                            <td>{{ $category->user_id }}</td>
											<td>{{ $category->title }}</td>
											<td>{{ $category->description }}</td>
											<td>{{ $category->image }}</td>
											{{-- <td>{{ $category->last_used_at }}</td> --}}
                                             
                                            <td>
                                                <form action="{{ route('category.destroy',$category->id) }}" method="POST">
                                                    <a  href="{{ route('category.show',$category->id) }}"class="text-green-500 hover:text-purple-700"><img class="inline"src="../css/src/eye.svg">Mostrar</a>
                                                    <a href="{{ route('category.edit',$category->id) }}"class="text-blue-500 hover:text-purple-700"><img class="inline"src="../css/src/document.svg">Editar</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="text-red-500" type="submit"><img class="inline" src="../css/src/trash.svg">Borrar</button>
                                                </form>
                                            </td>
                                             </div>
                                        </tr>
                                    </div>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
               
            </div>
        </div>
    </div>
   
@endsection

resources/views/category/show.blade.php
@extends('layouts.web')

@section('title','Mostrar')
    {{ $category->name ?? '' }}
{{-- @endsection --}}

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="">
                            <h1 class="text-center text-white p-2 font-bold text-xl mb-2 bg-gray-900">Categorias</h1>
                        </div>
                        <div class="float-right">
                            <a class="bg-purple-600 text-white text-xl font-bold" href="{{ route('category.index') }}"><img class="inline"src="../css/src/arrow-left.svg"> Regresar</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Title:</strong>
                            {{ $category->title }}
                        </div>
                        <div class="form-group">
                            <strong>Description:</strong>
                            {{ $category->description }}
                        </div>
                        <div class="form-group">
                            <strong>Image:</strong>
                            {{ $category->image }}
                        </div>
                       {{--  <div class="form-group">
                            <strong>Last Used At:</strong>
                            {{ $category->last_used_at }}
                        </div> --}}
                        @livewire('category-component')
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection