routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\ForumController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('home');
}); */


Route::get('/',  HomeController::class)->name('home');
Route::get('nosotros',  HomeController::class)->name('nosotros');
/* Rutas de curso */
Route::get('course', [ CourseController::class,'index'])->name('course.index');

Route::get('course/create', [ CourseController::class,'create'])->name('course.create');

Route::post('course/', [ CourseController::class,'store'])->name('course.store');

Route::get('course/texto',[CourseController::class,'texto'])->name('course.texto');

Route::get('course/{course}', [ CourseController::class,'show'])->name('course.show');

/* Rutas del post */
Route::get('post', [ PostController::class,'post'])->name('post');

Route::get('post', [ PostController::class,'index'])->name('post.index');

Route::get('post/create', [ PostController::class,'create'])->name('post.create');

Route::post('post/', [ PostController::class,'store'])->name('post.store');

Route::get('post/{post}', [ PostController::class,'show'])->name('post.show');

/* Rutas del foro */
Route::get('forum', [ ForumController::class,'forum'])->name('forum');

Route::get('forum', [ ForumController::class,'index'])->name('forum.index');

Route::get('forum/create', [ ForumController::class,'create'])->name('forum.create');

Route::post('forum/', [ ForumController::class,'store'])->name('forum.store');

Route::get('forum/{post}', [ ForumController::class,'show'])->name('forum.show');

/* Rutas del comentarios */
Route::get('comment', [ CommentController::class,'comment'])->name('comment');

Route::get('comment', [ CommentController::class,'index'])->name('comment.index');

Route::get('comment/create', [ CommentController::class,'create'])->name('comment.create');

Route::post('comment/', [ CommentController::class,'store'])->name('comment.store');

Route::get('comment/{comment}', [ CommentController::class,'show'])->name('comment.show');

/* Ruta de category */
Route::get('category', [ CategoryController::class,'category'])->name('category');

Route::get('category', [ CategoryController::class,'index'])->name('category.index');

Route::get('category/create', [ CategoryController::class,'create'])->name('category.create');

Route::post('category/', [ CategoryController::class,'store'])->name('category.store');

Route::get('category/{category}', [ CategoryController::class,'show'])->name('category.show');


Route::resource('course', CourseController::class);
Route::resource('post',PostController::class);
Route::resource('forum',ForumController::class);
Route::resource('comment',CommentController::class);
Route::resource('category',CategoryController::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Comment
 *
 * @property $id
 * @property $user_id
 * @property $category_id
 * @property $title
 * @property $description
 * @property $created_at
 * @property $updated_at
 *
 * @property Category $category
 * @property User $user
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Comment extends Model
{
    
    static $rules = [
		'title' => 'required',
		'description' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['user_id','category_id','title','description'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function category()
    {
        return $this->hasOne('App\Models\Category', 'id', 'category_id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne('App\Models\User', 'id', 'user_id');
    }
    

}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use Illuminate\Http\Request;

/**
 * Class CommentController
 * @package App\Http\Controllers
 */
class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $comments = Comment::paginate();

        return view('comment.index', compact('comments'))
            ->with('i', (request()->input('page', 1) - 1) * $comments->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $comment = new Comment();
        return view('comment.create', compact('comment'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Comment::$rules);

        $comment = Comment::create($request->all());

        return redirect()->route('comments.index')
            ->with('success', 'Comment created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $comment = Comment::find($id);

        return view('comment.show', compact('comment'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $comment = Comment::find($id);

        return view('comment.edit', compact('comment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        request()->validate(Comment::$rules);

        $comment->update($request->all());

        return redirect()->route('comments.index')
            ->with('success', 'Comment updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $comment = Comment::find($id)->delete();

        return redirect()->route('comments.index')
            ->with('success', 'Comment deleted successfully');
    }
}

resources/views/comment/create.blade.php
@extends('layouts.web')

@section('title','crear')
 {{--    Create Comment
@endsection --}}

@section('content')
    <section class="content container-fluid">
        <div class="shadow-xl p-10 bg-gray-300 max-w-64 mt-8 rounded">
            <div class="w-full px-3 mr-2 text-center text-gray-800 font-bold text-xl mb-2  bg-gray-600">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Comentar</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('comment.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('comment.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/comment/edit.blade.php
@extends('layouts.web')

@section('title','Editar')
{{--     Update Comment
@endsection --}}

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Comment</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('comment.update', $comment->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('comment.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/comment/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body py-8 mx-auto max-w-screen-xl  sm:flex flex-grow-0 sm:p-5"">
        
        <div class="form-group">
            {{ Form::label('usuario_id') }}
            {{ Form::text('user_id', $comment->user_id, ['class' => 'form-control' . ($errors->has('user_id') ? ' is-invalid' : ''), 'placeholder' => 'Usuario Id']) }}
            {!! $errors->first('user_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('categoria_id') }}
            {{ Form::text('category_id', $comment->category_id, ['class' => 'form-control' . ($errors->has('category_id') ? ' is-invalid' : ''), 'placeholder' => 'Categoria Id']) }}
            {!! $errors->first('category_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('titulo') }}
            {{ Form::text('title', $comment->title, ['class' => 'form-control' . ($errors->has('title') ? ' is-invalid' : ''), 'placeholder' => 'Titulo']) }}
            {!! $errors->first('title', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('descripción') }}
            {{ Form::text('description', $comment->description, ['class' => 'form-control' . ($errors->has('description') ? ' is-invalid' : ''), 'placeholder' => 'Descripción']) }}
            {!! $errors->first('description', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
</div>

resources/views/comment/index.blade.php
@extends('layouts.web')

@section('title','Comentarios')
{{--     Comment
@endsection --}}

@section('content')
<h1 class="text-center text-white  font-bold text-xl mb-2  bg-gray-900">Comentarios</h1>
<section class="px-4 sm:px-6 lg:px-4 xl:px-6 pt-4 pb-4 sm:pb-6 lg:pb-4 xl:pb-2 space-y-1">
    
    <div class="w-full lg:max-w-full lg:flex">
        <div class="h-48 lg:h-auto lg:w-58 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden">
        </div>
<div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-gray-500 rounded-b lg:rounded-b-none lg:rounded-r p-1 flex flex-col justify-between leading-normal">
    
    <div class="mb-8">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Comment') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('comment.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        {{-- <th>No</th> --}}
                                        
										<th>User Id</th>
										{{-- <th>Category Id</th>  --}}
										<th>Title</th>
										<th>Description</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($comments as $comment)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $comment->user_id }}</td>
											<td>{{ $comment->category_id }}</td>
											<td>{{ $comment->title }}</td>
											<td>{{ $comment->description }}</td>
                                            <td>{{ $comment->image }}</></td>

                                            <td>
                                                <form action="{{ route('comment.destroy',$comment->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('comment.show',$comment->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('comment.edit',$comment->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
               
            </div>
        </div>
    </div>
@endsection

resources/views/comment/show.blade.php
@extends('layouts.web')

@section('title','Mostrar')
    {{ $comment->name ?? '' }}
{{-- @endsection --}}

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Comment</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('comment.index') }}">Volver</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>User Id:</strong>
                            {{ $comment->user_id }}
                        </div>
                        <div class="form-group">
                            <strong>Category Id:</strong>
                            {{ $comment->category_id }}
                        </div>
                        <div class="form-group">
                            <strong>Title:</strong>
                            {{ $comment->title }}
                        </div>
                        <div class="form-group">
                            <strong>Description:</strong>
                            {{ $comment->description }}
                        </div>
                        @livewire('comment-component')
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection