routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\ForumController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('home');
}); */


Route::get('/',  HomeController::class)->name('home');
Route::get('nosotros',  HomeController::class)->name('nosotros');
/* Rutas de curso */
Route::get('course', [ CourseController::class,'index'])->name('course.index');

Route::get('course/create', [ CourseController::class,'create'])->name('course.create');

Route::post('course/', [ CourseController::class,'store'])->name('course.store');

Route::get('course/texto',[CourseController::class,'texto'])->name('course.texto');

Route::get('course/{course}', [ CourseController::class,'show'])->name('course.show');

/* Rutas del post */
Route::get('post', [ PostController::class,'post'])->name('post');

Route::get('post', [ PostController::class,'index'])->name('post.index');

Route::get('post/create', [ PostController::class,'create'])->name('post.create');

Route::post('post/', [ PostController::class,'store'])->name('post.store');

Route::get('post/{post}', [ PostController::class,'show'])->name('post.show');

/* Rutas del foro */
Route::get('forum', [ ForumController::class,'forum'])->name('forum');

Route::get('forum', [ ForumController::class,'index'])->name('forum.index');

Route::get('forum/create', [ ForumController::class,'create'])->name('forum.create');

Route::post('forum/', [ ForumController::class,'store'])->name('forum.store');

Route::get('forum/{post}', [ ForumController::class,'show'])->name('forum.show');

/* Rutas del comentarios */
Route::get('comment', [ CommentController::class,'comment'])->name('comment');

Route::get('comment', [ CommentController::class,'index'])->name('comment.index');

Route::get('comment/create', [ CommentController::class,'create'])->name('comment.create');

Route::post('comment/', [ CommentController::class,'store'])->name('comment.store');

Route::get('comment/{comment}', [ CommentController::class,'show'])->name('comment.show');

/* Ruta de category */
Route::get('category', [ CategoryController::class,'category'])->name('category');

Route::get('category', [ CategoryController::class,'index'])->name('category.index');

Route::get('category/create', [ CategoryController::class,'create'])->name('category.create');

Route::post('category/', [ CategoryController::class,'store'])->name('category.store');

Route::get('category/{category}', [ CategoryController::class,'show'])->name('category.show');


Route::resource('course', CourseController::class);
Route::resource('post',PostController::class);
Route::resource('forum',ForumController::class);
Route::resource('comment',CommentController::class);
Route::resource('category',CategoryController::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Course.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Course
 *
 * @property $id
 * @property $user_id
 * @property $category_id
 * @property $title
 * @property $slug
 * @property $image
 * @property $description
 * @property $last_used_at
 * @property $created_at
 * @property $updated_at
 *
 * @property Category $category
 * @property User $user
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Course extends Model
{
    use HasFactory;
   static $rules = [
		'category_id' => 'required',
		'title' => 'required',
		'slug' => 'required',
		'image' => 'required',
		'description' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
    'user_id',
    'category_id',
    'title',
    'slug',
    'image',
    'description',
    'last_used_at'
];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function category()
    {
        return $this->hasOne('App\Models\Category', 'id', 'category_id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne('App\Models\User', 'id', 'user_id');
    }
    

}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Course;
use Illuminate\Http\Request;

/**
 * Class CourseController
 * @package App\Http\Controllers
 */
class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $course = Course::all();

        return view('course.index', compact('course'));
            
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courses = new Course();
        return view('course.create', compact('courses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){

        $course = new Course();

        $course->title = $request->title;
        $course->description = $request->description;
        $course->image = $request->image;
        $course->save();

        return $this->redirect()->route('course.index',$course->id);    }
   /*  public function store(Request $request)
    {
        request()->validate(Course::$rules);

        $course = Course::create($request->all());

        return redirect()->route('course.index')
            ->with('success', 'Curso creado exitosamente .');
    } */

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $course = Course::find($id);

        return view('course.show', compact('courses'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($course)
    {
        $courses = Course::find($course);

        return view('course.edit', compact('courses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Course $course
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Course $course)
    {
        request()->validate(Course::$rules);

        $course->update($request->all());

        return redirect()->route('course.index')
            ->with('success', 'Curso creado exitosamente');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $course = Course::find($id)->delete();

        return redirect()->route('course.index')
            ->with('success', 'Curso borrado');
    }
}

resources/views/course/create.blade.php
@extends('layouts.web')

@section('title','Crear')
  {{--   Create Course
@endsection --}}

@section('content')
<div class="float-right">
    <a href="{{ route('course.index') }}"><img class="inline"src="../css/src/arrow-left.svg"></a>
</div>
    <section class="content container-fluid">

        <div class="shadow-xl p-10 bg-gray-300 max-w-64 mt-8 rounded">
            <div class="w-full px-3 mr-2 text-center text-gray-800 font-bold text-xl mb-2  bg-gray-600">

                @includeif('partials.errors')

                
                    <div class="card-header">
                        <span class="card-title">Crear Curso</span>
                    </div>
                    <div class="card-body">
                        <form class="p-5" method="POST" action="{{ route('course.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('course.form')

                        </form>
                    </div>
                
            </div>
        </div>
    </section>
@endsection

resources/views/course/edit.blade.php
@extends('layouts.web')

@section('title','Editar')
{{--     Update Course
@endsection --}}

@section('content')
    <section class="content container-fluid">
        <div class="shadow-xl p-10 bg-gray-300 max-w-64 mt-8 rounded">
            <div class="col-md-12 w-full px-3 mr-2 text-center text-gray-800 font-bold text-xl mb-2  bg-gray-600">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Actualizar Curso</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('course.update', $course->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('course.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/course/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body py-4 mx-auto w-full  sm:flex flex-grow-0 sm:p-8">
        
        <div class="form-group">
            {{ Form::label('usuario_id') }}
            {{ Form::text('user_id', $course->user_id, ['class' => 'form-control' . ($errors->has('user_id') ? ' is-invalid' : ''), 'placeholder' => 'Usuario Id']) }}
            {!! $errors->first('user_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('categoria_id') }}
            {{ Form::text('category_id', $course->category_id, ['class' => 'form-control' . ($errors->has('category_id') ? ' is-invalid' : ''), 'placeholder' => 'Categoria Id']) }}
            {!! $errors->first('category_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('titulo') }}
            {{ Form::text('title', $course->title, ['class' => 'form-control' . ($errors->has('title') ? ' is-invalid' : ''), 'placeholder' => 'Titulo']) }}
            {!! $errors->first('title', '<div class="invalid-feedback">:message</p>') !!}
        </div>
  {{--       <div class="form-group">
            {{ Form::label('slug') }}
            {{ Form::text('slug', $course->slug, ['class' => 'form-control' . ($errors->has('slug') ? ' is-invalid' : ''), 'placeholder' => 'Slug']) }}
            {!! $errors->first('slug', '<div class="invalid-feedback">:message</p>') !!}
        </div> --}}
        <div class="form-group">
            {{ Form::label('imagen') }}
            {{ Form::text('image', $course->image, ['class' => 'form-control' . ($errors->has('image') ? ' is-invalid' : ''), 'placeholder' => 'Imagen']) }}
            {!! $errors->first('image', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('descripción') }}
            {{ Form::text('description', $course->description, ['class' => 'form-control' . ($errors->has('description') ? ' is-invalid' : ''), 'placeholder' => 'Descripción']) }}
            {!! $errors->first('description', '<div class="invalid-feedback">:message</p>') !!}
        </div>
      {{--   <div class="form-group">
            {{ Form::label('last_used_at') }}
            {{ Form::text('last_used_at', $course->last_used_at, ['class' => 'form-control' . ($errors->has('last_used_at') ? ' is-invalid' : ''), 'placeholder' => 'Last Used At']) }}
            {!! $errors->first('last_used_at', '<div class="invalid-feedback">:message</p>') !!}
        </div> --}}

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
</div>

resources/views/course/index.blade.php
@extends('layouts.web')

@section('title','cursos')
{{--     Course
@endsection --}}

@section('content')
<h1 class="text-center text-gray-700  font-bold text-xl mb-2  bg-gray-900">CURSOS</h1>
<section class="px-4 sm:px-6 lg:px-4 xl:px-6 pt-4 pb-4 sm:pb-6 lg:pb-4 xl:pb-2 space-y-1">
    
    <div class="w-full lg:max-w-full lg:flex">
        <div class="h-48 lg:h-auto lg:w-58 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden">
        </div>
<div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-gray-700 rounded-b lg:rounded-b-none lg:rounded-r p-1 flex flex-col justify-between leading-normal">
    
    <div class="mb-8">
        
      <img class="w-full h-64 rounded-b rounded-t mb-4 opacity-50" src="{{ asset('img/curso.jpg') }}">
      <p class="text-gray-400 text-justify">Comparte tus conocimientos, expresa tus ideas y opiniones de temas tecnólogicos, hemos creado este espacio para tí para que consigas todas tus metas.<br>Es fundamental ir marcándose metas para ir creciendo y evolucionando, y no quedarse anclado. Internet es un apoyo imprescindible, donde podremos encontrar prácticamente cualquier respuesta que busquemos. Google nos sacará de muchos apuros asi como tutoriales de youtube y varias guias que te ayudaran a crecer<br>
      abajo encontaras unos links para aprender gratis</p>
    </div>
  <div class="flex items-center">
   
    <p class="text-gray-700"> y luego compartir esos conocimientos</p>
          <ul>
          <li class="flex mb-4 text-gray-400"><img class=bg-purple-500 src="../css/src/arrow-right.svg"><a href="https://www.w3schools.com/"target="_blank">Documentacion</li></a>
          <li class="flex mb-4 text-gray-400"><img class=bg-purple-500src="../css/src/arrow-right.svg"><a href="https://code.org//"target="_blank">Codigo</li></a>
          <li class="flex mb-4 text-gray-400"><img class=bg-purple-500src="../css/src/arrow-right.svg"><a href="https://scratch.mit.edu/"target="_blank">Juegos</li></a>
          </ul>
</div>
</div>
</div>

{{-- creacion y buscador  --}}       
    <button class="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-4 py-2">
      <svg class="group-hover:text-light-blue-600 text-light-blue-500 mr-2" width="12" height="20" fill="currentColor">
        <path fill-rule="evenodd" clip-rule="evenodd" d="M6 5a1 1 0 011 1v3h3a1 1 0 110 2H7v3a1 1 0 11-2 0v-3H2a1 1 0 110-2h3V6a1 1 0 011-1z"/>
      </svg>
       <div class="float-rigth p-2 ">
          <a href="{{ route('course.create') }}"data-placement="rigth">
            {{ __('Crear un Curso') }}
          </a>
        </div>
    </button>
  
  <form class="relative">
    <svg width="20" height="20" fill="currentColor" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400">
      <path fill-rule="evenodd" clip-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" />
    </svg>
    <input class="focus:border-light-blue-500 focus:ring-1 focus:ring-light-blue-500 focus:outline-none w-1/2 text-sm text-black placeholder-gray-500 border border-gray-300 rounded-md py-2 pl-10" type="text" aria-label="Filter projects" placeholder="Filtrar Curso" />
  </form>
  {{-- table --}}
    <div class="container-fluid">
        <div class="row border">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header bg-gray-900 text-white font-bold ">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Todos los Cursos') }}
                            </span>

                            
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    
                        <div class="table-responsive w-full border-gray-500">
                            <table class="min-w-full divide-y divide-gray-400 border bg-gray-300">
                                <thead class="thead">
                                    <tr class="bg-gray-500 text-center">
                                
                                     
                                        
										<th scope="col" class="px-6 py-3 text-center text-l font-bold  text-gray-900 uppercase tracking-wider">User Id</th> 
										<th scope="col" class="px-6 py-3 text-center text-l font-bold  text-gray-900 uppercase tracking-wider">Categoría Id</th>
										<th scope="col" class="px-6 py-3 text-center text-l font-bold  text-gray-900 uppercase tracking-wider">Titulo</th>
										
										
										<th scope="col" class="px-6 py-3 text-center text-l font-bold  text-gray-900 uppercase tracking-wider">Descripción</th>
                                        <th scope="col" class="px-6 py-3 text-center text-l font-bold  text-gray-900 uppercase tracking-wider">Imagen</th> 
                                        <th scope="col" class="px-6 py-3 text-center text-l font-bold  text-gray-900 uppercase tracking-wider">Acciones</th>
										

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody class="text-center w-full lg:max-w-full  lg:divide-y divide-gray-400">
                                    @foreach ($course as $course)
                                        <tr >
                                            {{-- <td>{{ ++$i }}</td> --}} 
                                            
										   <td>{{ $course->user_id }}</td>
											<td>{{ $course->category_id }}</td>
											<td>{{ $course->title }}</td>
											
											<td>{{ $course->image }}</td>
											<td>{{ $course->description }}</td>
											
                                            
                                            <td>
                                                <form action="{{ route('course.destroy',$course->id) }}" method="POST">
                                                    <a  href="{{ route('course.show',$course->id) }}"class="text-green-500 hover:text-purple-700 mr-4"><img class="inline"src="../css/src/eye.svg">Mostrar</a>
                                                    <a  href="{{ route('course.edit',$course->id) }}"class="text-blue-500 hover:text-purple-700 ml-8"><img class="inline"src="../css/src/document.svg">Editar</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="text-red-500" type="submit"><img class="inline" src="../css/src/trash.svg">Borrar</button>
                                                </form>
                                            </td>
                                           
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
@endsection

resources/views/course/show.blade.php
@extends('layouts.web')

@section('title','Mostrar')
    {{ $course->name ?? '' }}
{{-- @endsection --}}

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Cursos</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('course.index') }}">Volver</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>User Id:</strong>
                            {{ $course->user_id }}
                        </div>
                        <div class="form-group">
                            <strong>Category Id:</strong>
                            {{ $course->category_id }}
                        </div>
                        <div class="form-group">
                            <strong>Title:</strong>
                            {{ $course->title }}
                        </div>
                        <div class="form-group">
                            <strong>Slug:</strong>
                            {{ $course->slug }}
                        </div>
                        <div class="form-group">
                            <strong>Image:</strong>
                            {{ $course->image }}
                        </div>
                        <div class="form-group">
                            <strong>Description:</strong>
                            {{ $course->description }}
                        </div>
                        {{-- <div class="form-group">
                            <strong>Last Used At:</strong>
                            {{ $course->last_used_at }}
                        </div> --}}
                        @livewire('course-component')
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection